services:
  mysql:
    container_name: mysqldb
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=my_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    networks:
      - my-network
    volumes:
      - mysql:/data/mysql

  backend:
    container_name: backend_mysql
    build: .
    ports:
      - '8080:8080'
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  mysql: